### ISSUE TITLE
Fix builds

### ISSUE THREAD

**Issue by alenrajsp** [firefly-cpp/sport-activities-features-gui#24]
@firefly-cpp I can see in the Github actions that the 3.9 version of Python is also used. This won't work because the repo depends on 3.10 as mentioned in #16  https://github.com/firefly-cpp/sport-activities-features-gui/actions/runs/5539313014/jobs/10110146140?pr=23

Maybe we could only build for 3.10 and 3.11?

**Comment by firefly-cpp** [comment]
Yes
